name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setting a .env file
        run: cp .env.example .env
      - name: Build the stack
        run: docker-compose up -d
